// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://otwzgdbznlvzhmdkhhbq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im90d3pnZGJ6bmx2emhtZGtoaGJxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM2Mzk5NTAsImV4cCI6MjA2OTIxNTk1MH0.4707i3xBkthQimw5MMoQbRSGnoLoeuHKUzqm0YD6ZGU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});